# Generated by Django 5.1.7 on 2025-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0006_loan_remaining_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('loan_repayment', 'Loan Repayment')], default='deposit', max_length=15),
        ),
    ]
