# Generated by Django 5.1.7 on 2025-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0008_member_savings_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('loan_repayment', 'Loan Repayment'), ('transfer', 'Transfer')], default='deposit', max_length=15),
        ),
    ]
