# Generated by Django 5.1.7 on 2025-03-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0009_transaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
